---
title: "Value_Chain_Visualization"
format: html
---

# Purpose and Objective

Resource-Product Value chain analysis and visualization using I-O accounts as a data source.

A premise of this project is that double-entry I-O accounts contain a sufficient data set to derive directed acyclical graphs that can in turn be visualized. The graph (composed of nodes and edges) depicts the order and sequence of activities in a process that transforms a primary resource (e.g. wood from standing trees) into an end product (e.g., electricity generated by burning wood - biomass power generation). Graphs of this type are commonly referred to as "supply chains" or "resource value chains" or "resource-product value chains (RPVC)".

This project describes and illustrates methods used extract and visualize RPVCs from I-O accounts.

## 1. National Income and Product Accounts

Input-Output accounts are an artifact in a System of National Accounts or SNA (also referred to as National Income and Product Accounts or NIPA). Fundamental accounting identities hold for NIPA accounts and I-O accounts inherit the same identities.

National Income and Product identities: $$
\begin{align}
  v = c+i+g+(e-m)   && \text{(National Income = National Product)}\\
  m+v = c+i+g+e     && \text{(GNI + imports = GNP)}\\
  m+v = f     && \text{(GNI = Total Final Demand = f)}\\
\end{align}
$$

I-O accounts add an intermediate output variable to the identity to introduce the concept of total industry output:

$$
\begin{align}
  m+v = x+f     && \text{(x=intermediate output; (x+f) and (m+v)= total output)}\\
\end{align}
$$

## 2. Core Form I-O Accounts

### 2.1 Core Form I-O Accounts

The fundamental accounting identities (i.e., double-entry identities) for I-O are shown in equations (1) and (2) below. These equations describe the *Core Form* (vs the *Leontief Form*) of I-O accounts

$$
\begin{align}
    X + f = x && \text{(Intermediate Demand + Final Demand = Total Output) (1)}\\
    V + M = q && \text{(Value Added + Imports = Total Outlay) (2)}\\
\end{align}
$$

### 2,2 Direct input coefficients

Using the *Core Form* equations (1) and (2), and assuming a multi-sector set of accounts, we cannot associate the multi-sector pattern of inputs (V and M) with the multi-sector pattern of final products f. In order to do this, we need algebraically transform the *Core Form* accounts into the *Leontief Form* of the same I-O accounts. To accomplish the algebraic transformation, start with the assumption that the pattern of inputs for an activity's product can be given by a vector of *direct coefficients* as shown in equations (3) - (5).

$$
\begin{align}
    \hat{q}^{-1}X = _{i}A && \text{(Inter-industry Direct Input Coefficients matrix iA) (3)}\\
    \hat{q}^{-1}V = _{v}A && \text{(Value Added Direct Input Coefficients matrix vA) (4)}\\
    \hat{q}^{-1}M = _{m}A && \text{(Import Direct Input Coefficients matrix mA) (5)}\\
\end{align}
$$

## 3. Inter-Industry Adjacency Matrix

### 3.1 Identifying an RPVC Path in an Adjacency Matrix

The ~i~***A*** matrix is commonly referred to as the *Direct Coefficients* matrix. The term *Direct* refers to the *one-step* relationships between an industry activity and its input suppliers. That is, each industry activity is one transaction (i.e., *one step*) removed from each of its suppliers. In aggregate, each industry activity and its suppliers have a *one-to-many* relationship (i.e., one activity has many suppliers) and this *one-to-many* relationship is represented by a column vector in the ~i~***A*** matrix.

An *Adjacency Matrix* derived from the ~i~***A*** matrix can be used to determine the number of one-step relationships (i.e., transactions) between any pair of purchasing and suppling activities. In other words, an *Adjacency Matrix* can reveal the path and distance (number of steps) between an origin activity and a destination activity (i.e., an RPVC).

Derive adjacency matrix ***B*** from the ~i~***A*** matrix. Successive powers of ***B^n^*** will identify successive paths of step-length ***n***.

To illustrate an adjacency matrix, consider a portion of an ~i~***A*** matrix with only wood-related activities. Assume industry ***1*** is *Grow*, industry ***2*** is *Harvest*, industry ***3*** is *Saw Mill*, industry ***4*** is *Residuals*, industry ***5*** is *Bio-Power*, and industry ***6*** is *Other*. Assume the commodity produced by industry ***1*** is *Stumpage* (*m^3^* of solid wood), the commodity produced by industry ***2*** is *Logs* (containing *m^3^* of solid wood), the commodity produced by industry ***3*** is *Dimension Lumber* (containing *m^3^* of solid wood), the commodity produced by industry ***4*** is *Sawdust Residuals* (containing *m^3^* of solid wood), the commodity produced by industry ***5*** is *Electricity* (generated by using *m^3^* of solid wood *Sawdust Residuals* as fuel), and commodity produced by industry ***6*** is *Other*.

The complete matrix ~i~A:

$$\mathbf{A} = \left[\begin{array}
{rrr}
a_{11} & a_{12} & a_{13} & a_{14} & a_{15} & a_{16} \\
a_{21} & a_{22} & a_{23} & a_{24} & a_{25} & a_{26} \\
a_{31} & a_{32} & a_{33} & a_{34} & a_{35} & a_{36} \\
a_{41} & a_{42} & a_{43} & a_{44} & a_{45} & a_{46} \\
a_{51} & a_{52} & a_{53} & a_{54} & a_{55} & a_{56} \\
a_{61} & a_{62} & a_{63} & a_{64} & a_{65} & a_{66} \\
\end{array}\right]
$$

The non-zero elements of matrix ~i~A:

$$\mathbf{A} = \left[\begin{array}
{rrr}
a_{11} & a_{12} & 0 & 0 & 0 & 0 \\
0 & a_{22} & a_{23} & 0 & 0 & 0 \\
0 & 0 & a_{33} & a_{34} & 0 & 0 \\
0 & 0 & 0 & a_{44} & a_{45} & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
\end{array}\right]
$$

Adjacency matrix B^1^ (no 1-step path between Activity 5 and Activity 1 indicated by b~15~ =0):

$$\mathbf{B} = \left[\begin{array}
{rrr}
1 & 1 & 0 & 0 & 0 & 0 \\
0 & 1 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
\end{array}\right]
$$

Adjacency Matrix B^2^ (no 2-step path between Activity 5 and Activity 1 indicated by b~15~ =0):

$$\mathbf{B} = \left[\begin{array}
{rrr}
1 & 2 & 1 & 0 & 0 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 \\
0 & 0 & 1 & 2 & 1 & 0 \\
0 & 0 & 0 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
\end{array}\right]
$$

Adjacency Matrix B^3^ (no 3-step path between Activity 5 and Activity 1 indicated by b~15~ =0):

$$\mathbf{B} = \left[\begin{array}
{rrr}
1 & 3 & 3 & 1 & 0 & 0 \\
0 & 1 & 3 & 3 & 1 & 0 \\
0 & 0 & 1 & 3 & 2 & 0 \\
0 & 0 & 0 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
\end{array}\right]
$$

Adjacency Matrix B^4^ (one 4-step path between Activity 5 and Activity 1 indicated by b~15~ =1):

$$\mathbf{B} = \left[\begin{array}
{rrr}
1 & 4 & 6 & 4 & 1 & 0 \\
0 & 1 & 4 & 5 & 2 & 0 \\
0 & 0 & 1 & 2 & 1 & 0 \\
0 & 0 & 0 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
\end{array}\right]
$$

The *trace* of the *path* of *length* 4 from Activity 5 to Activity 1 in ***B***:

**step 1: (b~55~ \> b~45~), step 2: (b~43~ \> b~33~), step 3: (b~32~ \> b~22~), step 4: (b~21~ \> b~11~)**

A *path* like this can be used below to determine the order and number of steps (column-space expansions) necessary to decompose a specific RPVC from a *Leontief Form* product vector.

### 3.2 Visualizing a Path in an Adjacency Graph

#### 3.2.1 Extractung Nodes and Edges from I-O Matrices

#### 3.2.2 Visualization of a Path in a Graph

## 4. Leontief Form I-O Accounts:

*Leontief-Form* I-O accounts map multi-sector inputs to multi-sector output. This is achieved by deriving a multi-sector transformation matrix to transform the *Core Form* I-O accounts into the *Leontief-Form* I-O accounts. The transformation from *Core Form* to *Netput Form* to *Leontief Form* I-O accounts (including the derivation of a "multiplier matrix") is derived algebraically as follows:

$$
\begin{align}
    X+f=x && \text{(Core Form I-O Accounts) (6)}\\
    X=_{i}Ax && \text{(Substitute) (7)}\\
    _{i}Ax+f=x && \text{(Core Form I-O Accounts) (8)}\\
        f=(I-_{i}A)x && \text{(Rearrange; Netput Form of I-O Accounts) (9)}\\
    N = (I-_{i}A)^{-1} && \text{(Substitute) (10)}\\
        f=Nx && \text{(Netput Form of I-O Accounts) (11)}\\
    x = N^{-1}f && \text{(Rearrange; Leontief Form I-O Accounts) (12)}\\
    Z = N^{-1} && \text{(Substitute) (13)}\\
    x = Zf && \text{(Leontief Form I-O Accounts) (14)}\\
\end{align}
$$

### 4.1 Leontief Form, Output Space (Primal)

Accounting identites:

$$
\begin{align}
    x = Zf && \text{(Leontief Form for Total Output) (15)}\\
\end{align}
$$

Where *x*:

$$\mathbf{x} = \left[\begin{array}
{rrr}
x_{1} \\
x_{2} \\
x_{3} \\
x_{4} \\
x_{5} \\
x_{6} \\
\end{array}\right]
$$

Vector *f*:

$$\mathbf{f} = \left[\begin{array}
{rrr}
f_{1} \\
f_{2} \\
f_{3} \\
f_{4} \\
f_{5} \\
f_{6} \\
\end{array}\right]
$$

Matrix *Z*:

$$\mathbf{Z} = \left[\begin{array}
{rrr}
z_{11} & z_{12} & z_{13} & z_{14} & z_{15} & z_{16} \\
z_{21} & z_{22} & z_{23} & z_{24} & z_{25} & z_{26} \\
z_{31} & z_{32} & z_{33} & z_{34} & z_{35} & z_{36} \\
z_{41} & z_{42} & z_{43} & z_{44} & z_{45} & z_{46} \\
z_{51} & z_{52} & z_{53} & z_{54} & z_{55} & z_{56} \\
z_{61} & z_{62} & z_{63} & z_{64} & z_{65} & z_{66} \\
\end{array}\right]
$$

### 4.2 Leontief Form, Input Space (Dual)

Accounting identites:

$$
\begin{align}
    v = \widehat{_{v}A}Zf && \text{(Leontief Form for Total Value Added) (16)}\\
    m = \widehat{_{m}A}Zf && \text{(Leontief Form for Total Imports) (17)}\\
    (v+m) = (\widehat{_{v}A}Zf+\widehat{_{m}A}Zf) && \text{(Leontief Form for Total Primary Inputs (v+m)) (18)}\\
\end{align}
$$

Total Value Added vector v:

$$\mathbf{v} = \left[\begin{array}
{rrr}
v_{1} \\
v_{2} \\
v_{3} \\
v_{4} \\
v_{5} \\
v_{6} \\
\end{array}\right]
$$

Total Value Added Direct Coefficients matrix $\widehat{_{v}A}$:

$$\mathbf {\widehat{_{v}A}} = \left[\begin{array}
{rrr}
a_{11} & 0 & 0 & 0 & 0 & 0 \\
0 & a_{22} & 0 & 0 & 0 & 0 \\
0 & 0 & a_{33} & 0 & 0 & 0 \\
0 & 0 & 0 & a_{44} & 0 & 0 \\
0 & 0 & 0 & 0 & a_{55} & 0 \\
0 & 0 & 0 & 0 & 0 & a_{66} \\
\end{array}\right]
$$

Vector f:

$$\mathbf{f} = \left[\begin{array}
{rrr}
f_{1} \\
f_{2} \\
f_{3} \\
f_{4} \\
f_{5} \\
f_{6} \\
\end{array}\right]
$$

Matrix Z:

$$\mathbf{Z} = \left[\begin{array}
{rrr}
z_{11} & z_{12} & z_{13} & z_{14} & z_{15} & z_{16} \\
z_{21} & z_{22} & z_{23} & z_{24} & z_{25} & z_{26} \\
z_{31} & z_{32} & z_{33} & z_{34} & z_{35} & z_{36} \\
z_{41} & z_{42} & z_{43} & z_{44} & z_{45} & z_{46} \\
z_{51} & z_{52} & z_{53} & z_{54} & z_{55} & z_{56} \\
z_{61} & z_{62} & z_{63} & z_{64} & z_{65} & z_{66} \\
\end{array}\right]
$$

Intermediate product matrix $\widehat{_{v}A}Z$:

$$\mathbf{Z} = \left[\begin{array}
{rrr}
(_{v}a_{11}*z_{11}) & (_{v}a_{11}*z_{12}) & (_{v}a_{11}*z_{13}) & (_{v}a_{11}*z_{14}) & (_{v}a_{11}*z_{15}) & (_{v}a_{11}*z_{16}) \\
(_{v}a_{21}*z_{21}) & (_{v}a_{21}*z_{22}) & (_{v}a_{21}*z_{23}) & (_{v}a_{21}*z_{24}) & (_{v}a_{21}*z_{25}) & (_{v}a_{21}*z_{26}) \\
(_{v}a_{31}*z_{31}) & (_{v}a_{31}*z_{32}) & (_{v}a_{31}*z_{33}) & (_{v}a_{31}*z_{34}) & (_{v}a_{31}*z_{35}) & (_{v}a_{31}*z_{36}) \\
(_{v}a_{41}*z_{41}) & (_{v}a_{41}*z_{42}) & (_{v}a_{41}*z_{43}) & (_{v}a_{41}*z_{44}) & (_{v}a_{41}*z_{45}) & (_{v}a_{41}*z_{46}) \\
(_{v}a_{51}*z_{51}) & (_{v}a_{51}*z_{52}) & (_{v}a_{51}*z_{53}) & (_{v}a_{51}*z_{54}) & (_{v}a_{51}*z_{55}) & (_{v}a_{51}*z_{56}) \\
(_{v}a_{51}*z_{61}) & (_{v}a_{51}*z_{62}) & (_{v}a_{51}*z_{63}) & (_{v}a_{51}*z_{64}) & (_{v}a_{51}*z_{65}) & (_{v}a_{51}*z_{66}) \\
\end{array}\right]
$$

Total Value Added vector v in explicit computational form $\widehat{_{v}A}Zf$:

$$\mathbf{v} = \left[\begin{array}
{rrr}
((_{v}a_{11}*z_{11})*f_{1}) & +((_{v}a_{11}*z_{12})*f_{2}) & +((_{v}a_{11}*z_{13})*f_{3}) & +((_{v}a_{11}*z_{14})*f_{4}) & +((_{v}a_{11}*z_{15})*f_{5}) & +((_{v}a_{11}*z_{16})*f_{6}) \\
((_{v}a_{21}*z_{21})*f_{1}) & +((_{v}a_{21}*z_{22})*f_{2}) & +((_{v}a_{21}*z_{23})*f_{3}) & +((_{v}a_{21}*z_{24})*f_{4}) & +((_{v}a_{21}*z_{25})*f_{5}) & +((_{v}a_{21}*z_{26})*f_{6}) \\
((_{v}a_{31}*z_{31})*f_{1}) & +((_{v}a_{31}*z_{32})*f_{2}) & +((_{v}a_{31}*z_{33})*f_{3}) & +((_{v}a_{31}*z_{34})*f_{4}) & +((_{v}a_{31}*z_{35})*f_{5}) & +((_{v}a_{31}*z_{36})*f_{6}) \\
((_{v}a_{41}*z_{41})*f_{1}) & +((_{v}a_{41}*z_{42})*f_{2}) & +((_{v}a_{41}*z_{43})*f_{3}) & +((_{v}a_{41}*z_{44})*f_{4}) & +((_{v}a_{41}*z_{45})*f_{5}) & +((_{v}a_{41}*z_{46})*f_{6}) \\
((_{v}a_{51}*z_{51})*f_{1}) & +((_{v}a_{51}*z_{52})*f_{2}) & +((_{v}a_{51}*z_{53})*f_{3}) & +((_{v}a_{51}*z_{54})*f_{4}) & +((_{v}a_{51}*z_{55})*f_{5}) & +((_{v}a_{51}*z_{56})*f_{6}) \\
((_{v}a_{51}*z_{61})*f_{1}) & +((_{v}a_{51}*z_{62})*f_{2}) & +((_{v}a_{51}*z_{63})*f_{3}) & +((_{v}a_{51}*z_{64})*f_{4}) & +((_{v}a_{51}*z_{65})*f_{5}) & +((_{v}a_{51}*z_{66})*f_{6}) \\
\end{array}\right]
$$

### 4.3 Column space expansion of Leontief Form I-O OUtput Space:

Equation:

$$
\begin{align}
    x = Zf && \text{(Leontief Form for Total Output) (15)}\\
    O = Z\hat{f} && \text{($\hat{f}$ is a diagonal matrix of final demands; O is the column space of x)}\\
\end{align}$$

Where: Vector $\hat{f}$:

$$\mathbf {f} = \left[\begin{array}
{rrr}
x_{1} \\
x_{2} \\
x_{3} \\
x_{4} \\
x_{5} \\
x_{6} \\
\end{array}\right]
$$

Vector f:

$$\mathbf{f} = \left[\begin{array}
{rrr}
f_{11} & 0 & 0 & 0 & 0 & 0 \\
0 & f_{22} & 0 & 0 & 0 & 0 \\
0 & 0 & f_{33} & 0 & 0 & 0 \\
0 & 0 & 0 & f_{44} & 0 & 0 \\
0 & 0 & 0 & 0 & f_{55} & 0 \\
0 & 0 & 0 & 0 & 0 & f_{66} \\
\end{array}\right]
$$

Matrix Z:

$$\mathbf{Z} = \left[\begin{array}
{rrr}
z_{11} & z_{12} & z_{13} & z_{14} & z_{15} & z_{16} \\
z_{21} & z_{22} & z_{23} & z_{24} & z_{25} & z_{26} \\
z_{31} & z_{32} & z_{33} & z_{34} & z_{35} & z_{36} \\
z_{41} & z_{42} & z_{43} & z_{44} & z_{45} & z_{46} \\
z_{51} & z_{52} & z_{53} & z_{54} & z_{55} & z_{56} \\
z_{61} & z_{62} & z_{63} & z_{64} & z_{65} & z_{66} \\
\end{array}\right]
$$

Column-space expansion Matrix O:

$$\mathbf{O} = \left[\begin{array}
{rrr}
o_{11} & o_{12} & o_{13} & o_{14} & o_{15} & o_{16} \\
o_{21} & o_{22} & o_{23} & o_{24} & o_{25} & o_{26} \\
o_{31} & o_{32} & o_{33} & o_{34} & o_{35} & o_{36} \\
o_{41} & o_{42} & o_{43} & o_{44} & o_{45} & o_{46} \\
o_{51} & o_{52} & o_{53} & o_{54} & o_{55} & o_{56} \\
o_{61} & o_{62} & o_{63} & o_{64} & o_{65} & o_{66} \\
\end{array}\right]
$$

### 4.5 Visualization of Tier 1 Column Space Expansion

TBD

### 4.6 Column space expansion of Leontief Form I-O Input Space:

TBD

### 4.7 Visualization of Tier 1 Column Space Expansion

## 5. Column Space Expansion of RPVCs

### 5.1 Supply Chain Tier 1 Column Space Expansion of Total Output of Vector o~5~

***SECTION 3.3 TBD!!!!***

Column space expansion of output vector o~5~:

$$
\begin{align}
    o = Zf && \text{(Leontief transformation function)}\\
    O = Z\hat{f} && \text{(f-hat is a diagonal matrix of intermediate demands by Biopwr; O is the column space of o)}\\
\end{align}
$$

(Product Electricity from Biomass Power Generation) Vector o~5~:

$$\mathbf{o_5} = \left[\begin{array}
{rrr}
o_{15} \\
o_{25} \\
o_{35} \\
o_{45} \\
o_{55} \\
o_{65} \\
\end{array}\right]
$$

Column space expansion of output vector o~5~:

$$
\begin{align}
    o = Zf && \text{(Leontief transformation function)}\\
    O = Z\hat{f} && \text{(f-hat is a diagonal matrix of intermediate demands by Biopwr; O is the column space of o)}\\
\end{align}
$$

Matrix O:

$$\mathbf{O} = \left[\begin{array}
{rrr}
o_{11} & o_{12} & o_{13} & o_{14} & o_{15} & o_{16} \\
o_{21} & o_{22} & o_{23} & o_{24} & o_{25} & o_{26} \\
o_{31} & o_{32} & o_{33} & o_{34} & o_{35} & o_{36} \\
o_{41} & o_{42} & o_{43} & o_{44} & o_{45} & o_{46} \\
o_{51} & o_{52} & o_{53} & o_{54} & o_{55} & o_{56} \\
o_{61} & o_{62} & o_{63} & o_{64} & o_{65} & o_{66} \\
\end{array}\right]
$$

### 5.2 Supply Chain Tier 2 Column Space Expansion of Total Output of Vector o~4~

### 5.3 Supply Chain Tier 3 Column Space Expansion of Total Output of Vector o~3~

### 5.4 Supply Chain Tier 4 Column Space Expansion of Total Output of Vector o~2~

## 6. Supply Chain Visualization

### 6.1 Assemble a Supply Chain Knowlegebase

### 6.2 Query Knowlegebase for Supply Chain Pattern

### 6.3 Visualization of Supply Chain
